- name: print message
  hosts: all
  vars:
    URL: www.kavya.com
    Project: Example
    tasks:
      - name: Print URL
        debug:
          msg: URL= {{ URL }}
      - name: Print URL from Task
        debug:
          msg: URL= {{ URL }}
        vars:
          URl: task.example.com
