- name: print message
  hosts: all
  vars_files:
    - eample-vars.yml
  vars:
    URL: www.kavya.com
    Project: Example
  vars_promt:
    - name: URL
      promt: Enter URL
      private: no
    tasks:
      - name: Print URL
        debug:
          msg: URL= {{ URL }}
      - name: Print URL from Task
        debug:
          msg: URL= {{ URL }}
    vars:
      URl: task.example.com



- name: Dynamic Vars
  hosts: all
  tasks:
    - name: Gather Date
      shell: date +%F
      register: out
    - name: Print Date
      debug:
       msg: Date = {{ out }}

