- name: Setup todo Project
  hosts: all
  become: yes
  tasks:
    - name: Apt Update
      apt:
        name: nginx
        update_cache: yes
        state: present

    - namr: Download foo.conf
      get_url
        url: http://        :8081/repository/frontend/frontend-{{APP_VERSION}}.zip
        dest: /tmp/frontend.zip

