- name: Setup todo Project
  hosts: all
  become: yes
  tasks:
    - name: Apt Update
      apt:
        name: nginx
        update_cache: yes
        state: present

    - name: Start Nginx
      systemd:
        state: started
        name: nginx
        enabled: yes

    - name: install node.js
        shell: apt-get install nodejs
        sudo: yes

    - name: Install npm
      npm:
        name: frontend
        path: /Idea/Projects/ansible




