- name: Setup todo Project
  hosts: all
  become: yes
  tasks:
    - name: Apt Update
      apt:
        name: nginx
        update_cache: yes
        state: present

    - name: Start Nginx
      systemd:
        state: started
        name: nginx
        enabled: yes

    - name: apt-get install node.js
      apt:
        name: node.js
        update_cache: yes
        state: present

    - name: Install npm
      npm:
        name: npm
        path: /home/kavya/IdeaProjects/ansible/frontend.yml




